### ISSUE TITLE
Live demo error 

### ISSUE THREAD

**Issue by cuongngosa** [kainino0x/wasm-call-js-from-rust#1] opened 2017-03-31 02:31 UTC
ReferenceError: Can't find variable: fetch

**Comment by kainino0x** [comment] 2017-03-31 02:51
`fetch` comes from the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), which as AFAIK should be available in all browsers which support WebAssembly. What's your browser and browser version?

**Comment by kainino0x** [comment] 2017-04-18 06:11
Since I can't reproduce this, I'll close it and reopen later if needed.

**Closed as completed by kainino0x** 2017-04-18 06:11 UTC
